// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yfycfcpyvupjpmngnxfi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlmeWNmY3B5dnVwanBtbmdueGZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwMTY5OTAsImV4cCI6MjA2MjU5Mjk5MH0.Laj4PWU58-eIc0Jxv6k1-66sxA2CLhW2onNtfAF7hFk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);